#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Sep 14 07:04:27 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim testbench_bram_behav -key {Behavioral:sim_1:Functional:testbench_bram} -tclbatch testbench_bram.tcl -protoinst "protoinst_files/bd_6f02.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim testbench_bram_behav -key {Behavioral:sim_1:Functional:testbench_bram} -tclbatch testbench_bram.tcl -protoinst "protoinst_files/bd_6f02.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

