#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Aug 12 13:18:58 CDT 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 07ed4253ce224be2afe0fc0be078be9c --incr --debug typical --relax --mt 8 --maxdelay -L xil_defaultlib -L xilinx_vip -L simprims_ver -L secureip --snapshot testbench_DDMTDSampler_time_impl -transport_int_delays -pulse_r 0 -pulse_int_r 0 -pulse_e 0 -pulse_int_e 0 xil_defaultlib.testbench_DDMTDSampler xil_defaultlib.glbl -log elaborate.log"
xelab -wto 07ed4253ce224be2afe0fc0be078be9c --incr --debug typical --relax --mt 8 --maxdelay -L xil_defaultlib -L xilinx_vip -L simprims_ver -L secureip --snapshot testbench_DDMTDSampler_time_impl -transport_int_delays -pulse_r 0 -pulse_int_r 0 -pulse_e 0 -pulse_int_e 0 xil_defaultlib.testbench_DDMTDSampler xil_defaultlib.glbl -log elaborate.log

