# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll.xci
# IP: The module: 'clock_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_pll'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll.xci
# IP: The module: 'clock_pll' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/rsaradhy/Work/trenz/vivado/project_1/project_1.srcs/sources_1/ip/clock_pll/clock_pll_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_pll'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
