# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/main.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_1/design_1_zynq_ultra_ps_e_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_1 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_smc_1/design_1_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_smc_1 || ORIG_REF_NAME==design_1_axi_smc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps8_0_200M_0/design_1_rst_ps8_0_200M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_ps8_0_200M_0 || ORIG_REF_NAME==design_1_rst_ps8_0_200M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_11/design_1_axi_bram_ctrl_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_11 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_7/design_1_axi_bram_ctrl_0_bram_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_bram_7 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_bram_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_12/design_1_axi_bram_ctrl_0_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_12 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_bram_8/design_1_axi_bram_ctrl_0_bram_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_bram_8 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_bram_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_bram1_0/design_1_axi_bram_ctrl_0_bram1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_bram1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_bram1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0/design_1_axi_bram_ctrl_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: ip/FIFO_10/FIFO_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_10 || ORIG_REF_NAME==FIFO_10} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
